# automation_green_washing_machine.yaml
alias: Green Energy Automation
description: "Start washing machine at the start of green period (robust)"
trigger:
  - platform: time
    at: "{{ states('sensor.green_time_start') }}"
condition:
  - condition: template
    value_template: "{{ states('sensor.green_time_start') not in ['', 'unknown', 'unavailable'] }}"
  - condition: state
    entity_id: switch.washing_machine
    state: "off"
action:
  - service: switch.turn_on
    target:
      entity_id: switch.washing_machine
  - service: persistent_notification.create
    data:
      title: "Green Energy Automation"
      message: >
        Washing machine started at {{ states('sensor.green_time_start') }}.
        Current state: {{ states('switch.washing_machine') }}
mode: single
